name: Node.js CI

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install
      - run: pnpm run build

  publish:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@timly'
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Release
        run: pnpm run release
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
